#!/bin/bash

echo "=================================================="
echo "  WatchLoop Backend Deployment to Render"
echo "=================================================="
echo ""
echo "✅ Frontend is live at:"
echo "   https://frontend-fawn-six-17.vercel.app"
echo ""
echo "🔄 Now deploying backend to Render..."
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1. Open your browser and go to:"
echo "   https://dashboard.render.com"
echo ""
echo "2. Sign in with GitHub using:"
echo "   areebashafqat2021@gmail.com"
echo ""
echo "3. Click 'New +' → 'Blueprint'"
echo ""
echo "4. Connect your repository:"
echo "   - Repository: Areeba-Shafqat/loop-engineering"
echo "   - Branch: master"
echo ""
echo "5. Render will detect render.yaml and show:"
echo "   - Service Name: watchloop-backend"
echo "   - Type: Web Service"
echo "   - Runtime: Python"
echo ""
echo "6. Click 'Apply' to start deployment"
echo ""
echo "7. Wait 2-3 minutes for deployment to complete"
echo ""
echo "8. Copy your backend URL (format: https://watchloop-backend-XXXX.onrender.com)"
echo ""
echo "=================================================="
echo "After deployment, run:"
echo "  ./update-frontend-env.sh <your-backend-url>"
echo "=================================================="
